# Generated by Django 2.2.1 on 2019-06-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '用例表'},
        ),
        migrations.AlterModelTable(
            name='case',
            table='Case',
        ),
    ]
